### ISSUE TITLE
Respring loop

### ISSUE THREAD

**Issue by stuie1** [Muirey03/Cr4shed#25] opened 2019-09-01 01:41 UTC
Ugh idk man cra4sed tweak puts me in respring loop have no clue why ugh also my phone crashes randomly like watching a video do something random crash no report idk ughhh crashreporter doesn’t work at telling me a respring problem can’t figure that one out

**Comment by jkole-4** [comment] 2019-09-02 03:30
Same here!! Got to the lockscreen once and it just locked up had to hard reboot it and uninstall :(

**Comment by XSp00pyX** [comment] 2019-09-02 16:11
Same issue as you guys here 😥

**Comment by NSExceptional** [comment] 2019-12-06 22:05
Can you post a crash log and provide some more info?

- iOS version
- Jailbreak and version
- Cr4shed version
- Are you using the CokePokes libraries?  He has some own versions of dependencies of this tweak that apparently cause crashes

**Comment by badger200** [comment] 2020-02-20 11:33
I experienced this several times last year on 12.4 unc0ver 3.6 on iPad Pro 9.7” WiFi, but I can’t recall the details of the fix. 

However, I DEFINITELY had major issues with cokepokes CrashReporter when Cr4shed was installed! So DEFINITELY get rid of all CokePokes CR stuff - TechSupport, libSymbolication, whatever ones have (CokePokes) in the name. Make sure they’re uninstalled, then install the BigBoss release, even if it has a slightly lower version number. 

My situation got a lot better then. 

Right now, I am coming off several months relative smooth stability, but I pruned a bunch of stuff using Choicy to prevent sloppy tweaks from loading in all sorts of unnecessary processes (like ones that hook com.apple.springboard in the /Library/MobileSubstrate/DynamicLibraries/TweakNameHere.plist file, but actually only get used by 1 app, like Netflix, or YouTube, etc.)

Well Choicy had been great up to that point. I didnt think i anything reckless, but nevertheless the result was my resprings would never get passed the black loading part where normally it switches to lock screen after 30-60 seconds.

I had to SSH in and mv 000_Choicy.dylib 000_Choicy.disabled and then issue sbreload. Boom instantly let me in. 

Finally when yesterday’s Choicy update didn’t fix it, I ended up renaming my /var/mobile/Library/Preferences/com.opa334.choicy.plist (or close to that name) so Choicy would get a totally fresh Settings - and that cured it. 

I will follow this post to see if we hopefully can get a resolution to all this, because when I first attempted using Cr4shed it was an absolute disaster (mostly because of CokePokes CrashReporter). 

I don’t get GitHub notifications reliably, so if you wanna be sure to get my attn email me sy Z clone Z 0044@g📬.com (delete the Z’s and translate the emoji).

**Comment by NSExceptional** [comment] 2020-02-20 15:44
I really don't think it's Cr4shed causing any respring loops, except for people using the CokePokes stuff. I think that's the long and short of it

**Comment by Muirey03** [comment] 2020-02-23 09:37
Cokepokes' CrashReporter was (and maybe still is?) broken on any jailbreak that isn't Chimera. It repeatedly caused the ReportCrash daemon to crash, which made it unable to report any crashes, and caused Cr4shed to show many crash notifications for ReportCrash (which is not a bug).

I'm closing this as I see no issue with Cr4shed here.

**Closed by Muirey03** 2020-02-23 09:37 UTC
Labels: awaiting response, bug

**Comment by stuie1** [comment] 2020-02-24 18:59
Crashed worked great on my iPhone 11 13.3 it didn’t work at all on ios12 works wonderfully now it’s awesome!! Everything works flawlessly on this iPhone 11

Stuart Bailey Jr
